FROM rabbitmq:3.13-management

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez -P /plugins && \
    echo "[rabbitmq_management,rabbitmq_prometheus,rabbitmq_delayed_message_exchange]." > /etc/rabbitmq/enabled_plugins &&\
    apt-get remove -y wget && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* \

EXPOSE 5672 15672