server:
  port: 18080
spring:
  application:
    name: lcsk42-gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos-password
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}


knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3


framework:
  gateway:
    allow-list:
      - path: /lcsk42-*-service/v3/api-docs
      - path: /lcsk42-admin-service/**
        method: GET
